spring:
  datasource: # Datasource 생성명령어.
    url: jdbc:log4jdbc:mysql://localhost:3306/datajpa
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 316201
#    hikari:
#      connection-timeout: 3000
#      maximum-pool-size: 5
#      max-lifetime: 30000

  batch:
    job:
      enabled: true
      names: jinmyeong
logging:
  level:
    jdbc:
      sqlonly: info
      connection: info
      sqltiming: info
      resultsettable: info